# Site settings
title: MohammadHossein Jamshidi
short_title: MH Jamshidi
email: jamshidi3d@gmail.com
url: https://github.com/jamshidi3d/portfolio
baseurl: /portfolio
# future: true
# timezone: GMT
about1: I'm a Ph.D. student of physics working on gravitation & cosmology. In 2012 I started my career in the game industry with modeling in the <a href="https://store.steampowered.com/app/353990/Parvaneh_Legacy_of_the_Lights_Guardians/" style="color:#FFFFFF">Parvaneh</a> project. Very soon in the same project, because of my background in math & physics and interest in technical arts, I started tool development and making physics-based assets. Since then I've done rigging and tool/shader development in Blender, Maya, 3dsMax, and also in Unity engine.

about2: In the academic field I gradually headed to computational physics, which was a good context for upgrading both my scientific and game-production skills (ofcourse, I love all areas in physics). Currently, together with research in cosmology (my old dream), I'm working on physics-based tools to help tech-artists & animators. 

description: MohammadHossein Jamshidi tech-arts portfolio
#"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "Physics, Programming, Tool development, Technical Art"
skills: "Physics Programmer - Technical Artist"
meta_author: Jamshidi MohammadHossein


# Google webmaster tools
google_verify: googlecaffd31da6f27a98.html

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Jamshidi3d

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 393E46 #80B3FF
  primary-rgb: "83,184,187" #"128,179,255"
  secondary: 232931 #FD6E8A
  secondary-dark: 121212 #A2122F

# Footer settings
footer:
  copyright: MH Jamshidi
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mohammadhossein-jamshidi-5a493366/

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
